#
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # annotations:
  #   deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    run: echoclient
  name: echoclient
  # namespace: latent
  namespace: latency
  # resourceVersion: "1114536"
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: echoclient
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        danm.k8s.io/interfaces: |
          [
            {"network":"default", "ip":"dynamic"},
            {"network":"ipvlan", "ip":"dynamic"}
          ]

      creationTimestamp: null
      labels:
        run: echoclient
    spec:
      containers:
      # - args:
      #   - bash
      - name: echoclient
        image: monkeysun555/debug_client:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 11111
        command: ["/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 30; done;"]
        resources: {}
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      nodeSelector:
        nodename: caas_master2
