# apiVersion: v1
# kind: Service
# metadata:
#   name: echoserver
#   labels:
#     app: echoserver
# spec:
#   type: NodePort
#   ports:
#   - port: 80
#     targetPort: 8000
#     nodePort: 31111
#     protocol: TCP
#     name: http
#   selector:
#     app: echoserver
# ---

apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  containers:
  - name: echoserver
    image: monkeysun555/centos_server:v1
    imagePullPolicy: Never
    ports:
    - containerPort: 8000
  nodeSelector:
    worktype: master